// Gallery Logic - Jekyll Automation Mode
document.addEventListener('DOMContentLoaded', async () => {
    const gallery = document.querySelector('.gallery');
    if (!gallery) return;

    // Determine Gallery Type
    const galleryType = gallery.getAttribute('data-type') || 'photography';

    // Paths
    let folderPath, thumbsPath, images, archiveImages;

    if (galleryType === 'drawings') {
        folderPath = 'images/drawings/';
        thumbsPath = 'images/drawings/'; // Drawings might not have thumb folder yet
        images = window.drawingImages || [];
    } else {
        // Photography
        // High Qual: stored in Originals
        folderPath = 'images/photography/Originals/';
        // Thumbs: stored in Thumbs
        thumbsPath = 'images/photography/Thumbs/';

        images = window.photographyImages || [];
        archiveImages = window.archiveImages || [];
    }

    // Reuseable Render Function
    function renderImages(imageList, container, isArchive = false) {
        if (!imageList || imageList.length === 0) {
            if (!isArchive) container.innerHTML = '<p style="text-align:center">No images found.</p>';
            else container.innerHTML = '<p style="text-align:center">No archived images found.</p>';
            return;
        }

        const currentFolderPath = isArchive ? folderPath + 'Archive/' : folderPath;
        const currentThumbsPath = isArchive ? thumbsPath + 'Archive/' : thumbsPath;

        imageList.forEach((filename, index) => {
            const item = document.createElement('div');
            item.className = 'gallery-item gallery-card';

            const imgContainer = document.createElement('div');
            imgContainer.className = 'card-image-container';

            const img = document.createElement('img');

            // Source Logic: 
            // - Thumb for Grid -> Replaced extension with .avif (generated by python script)
            // - Full for View/Lightbox -> Original filename (jpg/png/etc)

            // Derive thumb filename: MyPhoto.jpg -> MyPhoto.avif
            let thumbFilename = filename.substr(0, filename.lastIndexOf(".")) + ".avif";
            // Safety: if no extension valid, just append .avif
            if (filename.lastIndexOf(".") === -1) thumbFilename = filename + ".avif";

            img.src = currentThumbsPath + thumbFilename;
            // Store original high-res URL for Lightbox/View
            img.dataset.fullSrc = currentFolderPath + filename;
            img.alt = filename;
            img.className = 'gallery-img';

            // Lazy Load
            if (index < 4 && !isArchive) {
                img.loading = 'eager';
                img.fetchPriority = 'high';
            } else {
                img.loading = 'lazy';
            }

            imgContainer.appendChild(img);

            // Footer Actions
            const footer = document.createElement('div');
            footer.className = 'card-footer';
            footer.innerHTML = `
                <button class="card-action-btn view-btn" onclick="viewGridImage('${currentFolderPath + filename}')" title="View Original">
                    <span class="material-icons">visibility</span>
                    <span class="btn-text">Original</span>
                </button>
                <button class="card-action-btn share-btn" onclick="shareGridImage('${currentFolderPath + filename}')">
                    <span class="material-icons">share</span>
                </button>
            `;

            item.appendChild(imgContainer);
            item.appendChild(footer);
            container.appendChild(item);
        });

        // Re-init lightbox
        if (window.initLightbox) window.initLightbox();
    }

    // 1. Render Main Gallery
    // Shuffle Main Images Only
    function shuffleArray(array) {
        for (let i = array.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [array[i], array[j]] = [array[j], array[i]];
        }
    }
    if (images && images.length > 0) shuffleArray(images);

    gallery.innerHTML = '';
    renderImages(images, gallery, false);


    // 2. Handle Archive Logic
    const archiveBtn = document.getElementById('load-archive-btn');
    const archiveContainer = document.querySelector('.archive-gallery');

    if (archiveBtn && archiveContainer) {
        if (!archiveImages || archiveImages.length === 0) {
            archiveBtn.style.display = 'none'; // Hide if no archives
        } else {
            archiveBtn.addEventListener('click', () => {
                archiveBtn.style.display = 'none'; // Hide button after click
                archiveContainer.style.display = 'grid'; // Show grid
                renderImages(archiveImages, archiveContainer, true); // Render
            });
        }
    }


    // Global Grid Functions
    window.viewGridImage = function (url) {
        // url is passed from onclick, which we set to fullSrc in the render loop
        if (window.openLightboxByUrl) {
            // Pass true to preferOriginal -> Shows full JPG in lightbox
            window.openLightboxByUrl(url, true);
        } else {
            // Fallback if lightbox not loaded for some reason
            window.open(url, '_blank');
        }
    };

    window.shareGridImage = async function (url) {
        const fullUrl = window.location.origin + window.location.pathname + '#img=' + url.split('/').pop();
        if (navigator.share) {
            try {
                await navigator.share({ title: 'Check out this image', url: fullUrl });
            } catch (err) { console.log(err); }
        } else {
            try {
                await navigator.clipboard.writeText(fullUrl);
                alert('Link copied to clipboard!');
            } catch (err) { console.error(err); }
        }
    };

    if (window.initLightbox) window.initLightbox();
});
